/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;

import Controller.CrudMantenimiento;
import Controller.Sesion;
import java.awt.Image;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.event.MenuListener;
import javax.swing.event.MenuEvent;

/**
 *
 * @author jose9
 */
public class FrmInventario extends javax.swing.JFrame {
    
    
    Sesion ObjSesion = new Sesion();
    CrudMantenimiento crud = new CrudMantenimiento();
    String tipoUsuario = ObjSesion.getTipoUsuario();
    public FrmInventario(String tipoUsuario) {
        this.setUndecorated(true);
        initComponents();
        Image icon = new ImageIcon(getClass().getResource("/Assets/Pollo (2).jpeg")).getImage();
        setIconImage(icon);
        try {
            java.awt.Taskbar.getTaskbar().setIconImage(icon);
        } catch (Exception e) {
        }
        setSize(850,697);
        setLocationRelativeTo(null);
        setResizable(false);
        
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("ESCAPE"), "salir");
        getRootPane().getActionMap().put("salir", new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent e) {
            dispose();
            FrmPrincipal ObjPrincipal = new FrmPrincipal(tipoUsuario);
            ObjPrincipal .setVisible(true);
           }
        });
    }
        


    private FrmInventario() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtngComponentes = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        LblTitulo = new javax.swing.JLabel();
        LblIdPieza = new javax.swing.JLabel();
        TxtIdPieza = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        RdoHdd = new javax.swing.JRadioButton();
        RdoSsd = new javax.swing.JRadioButton();
        RdoRam = new javax.swing.JRadioButton();
        RdoPlaca = new javax.swing.JRadioButton();
        RdoFuente = new javax.swing.JRadioButton();
        RdoProcesador = new javax.swing.JRadioButton();
        RdoDisipador = new javax.swing.JRadioButton();
        RdoVentilador = new javax.swing.JRadioButton();
        LblCapacidad = new javax.swing.JLabel();
        TxtCapacidad = new javax.swing.JTextField();
        TxtCantidad = new javax.swing.JTextField();
        LblCantidad = new javax.swing.JLabel();
        TblDatos = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        CmbEstado = new javax.swing.JComboBox<>();
        LblEstado = new javax.swing.JLabel();
        BtnRegistrar = new javax.swing.JButton();
        BtnActualizar = new javax.swing.JButton();
        BtnBuscar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnuMenu = new javax.swing.JMenu();
        MnuIEquipos = new javax.swing.JMenuItem();
        MnuIPrincipal = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblTitulo.setText("Inventario");

        LblIdPieza.setText("Id componente");

        TxtIdPieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIdPiezaActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo Componente"));

        BtngComponentes.add(RdoHdd);
        RdoHdd.setText("HDD");
        RdoHdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdoHddActionPerformed(evt);
            }
        });

        BtngComponentes.add(RdoSsd);
        RdoSsd.setText("SSD");

        BtngComponentes.add(RdoRam);
        RdoRam.setText("Ram");
        RdoRam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdoRamActionPerformed(evt);
            }
        });

        BtngComponentes.add(RdoPlaca);
        RdoPlaca.setText("Placa madre");
        RdoPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdoPlacaActionPerformed(evt);
            }
        });

        BtngComponentes.add(RdoFuente);
        RdoFuente.setText("Fuente de poder");

        BtngComponentes.add(RdoProcesador);
        RdoProcesador.setText("Procesador");

        BtngComponentes.add(RdoDisipador);
        RdoDisipador.setText("Disipador");

        BtngComponentes.add(RdoVentilador);
        RdoVentilador.setText("Ventilador");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RdoHdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RdoSsd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RdoDisipador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(RdoRam, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RdoProcesador, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(RdoVentilador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RdoPlaca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RdoFuente))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RdoHdd)
                    .addComponent(RdoRam)
                    .addComponent(RdoProcesador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RdoSsd)
                    .addComponent(RdoPlaca)
                    .addComponent(RdoFuente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RdoDisipador)
                    .addComponent(RdoVentilador))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LblCapacidad.setText("Capacidad");

        LblCantidad.setText("Cantidad");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TblDatos.setViewportView(jTable1);

        CmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buen estado", "En reparacion", "Fuera de servicio", " " }));

        LblEstado.setText("Estado");

        BtnRegistrar.setText("Registrar");
        BtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarActionPerformed(evt);
            }
        });

        BtnActualizar.setText("Actualizar");

        BtnBuscar.setText("Buscar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(LblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtIdPieza)
                            .addComponent(LblIdPieza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnBuscar))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(LblEstado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CmbEstado, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TxtCapacidad, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                .addComponent(LblCapacidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TxtCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                .addComponent(LblCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnActualizar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(TblDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(LblTitulo)
                .addGap(18, 18, 18)
                .addComponent(LblIdPieza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtIdPieza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnBuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblCapacidad)
                            .addComponent(LblCantidad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(LblEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnRegistrar)
                            .addComponent(BtnActualizar)))
                    .addComponent(TblDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(250, Short.MAX_VALUE))
        );

        MnuMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Menu-right-outline.png"))); // NOI18N
        MnuMenu.setText("Menu");
        MnuMenu.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
                MnuMenuMenuCanceled(evt);
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
                MnuMenuMenuDeselected(evt);
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                MnuMenuMenuSelected(evt);
            }
        });

        MnuIEquipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Martz90-Circle-Addon2-Computer.24.png"))); // NOI18N
        MnuIEquipos.setText("Equipos");
        MnuIEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuIEquiposActionPerformed(evt);
            }
        });
        MnuMenu.add(MnuIEquipos);

        MnuIPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Graphicloads-100-Flat-Home.24.png"))); // NOI18N
        MnuIPrincipal.setText("Principal");
        MnuIPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuIPrincipalActionPerformed(evt);
            }
        });
        MnuMenu.add(MnuIPrincipal);

        jMenuBar1.add(MnuMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtIdPiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIdPiezaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIdPiezaActionPerformed

    private void RdoRamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdoRamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdoRamActionPerformed

    private void RdoHddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdoHddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdoHddActionPerformed

    private void RdoPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdoPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdoPlacaActionPerformed

    private void BtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnRegistrarActionPerformed

    private void MnuIPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuIPrincipalActionPerformed
        dispose();
        FrmPrincipal ObjPrincipal = new FrmPrincipal(tipoUsuario);
        ObjPrincipal .setVisible(true);
    }//GEN-LAST:event_MnuIPrincipalActionPerformed

    private void MnuMenuMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_MnuMenuMenuSelected
        MnuMenu.setIcon(new ImageIcon(getClass().getResource("/Assets/Menu-down-outline.png")));
    }//GEN-LAST:event_MnuMenuMenuSelected

    private void MnuMenuMenuDeselected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_MnuMenuMenuDeselected
        MnuMenu.setIcon(new ImageIcon(getClass().getResource("/Assets/Menu-right-outline.png")));
    }//GEN-LAST:event_MnuMenuMenuDeselected

    private void MnuMenuMenuCanceled(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_MnuMenuMenuCanceled
       MnuMenu.setIcon(new ImageIcon(getClass().getResource("/Assets/Menu-right-outline.png")));
    }//GEN-LAST:event_MnuMenuMenuCanceled

    private void MnuIEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuIEquiposActionPerformed
        dispose();
        FrmEquipos ObjEquipo = new FrmEquipos(tipoUsuario);
        ObjEquipo.setVisible(true);
    }//GEN-LAST:event_MnuIEquiposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmInventario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizar;
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnRegistrar;
    private javax.swing.ButtonGroup BtngComponentes;
    private javax.swing.JComboBox<String> CmbEstado;
    private javax.swing.JLabel LblCantidad;
    private javax.swing.JLabel LblCapacidad;
    private javax.swing.JLabel LblEstado;
    private javax.swing.JLabel LblIdPieza;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JMenuItem MnuIEquipos;
    private javax.swing.JMenuItem MnuIPrincipal;
    private javax.swing.JMenu MnuMenu;
    private javax.swing.JRadioButton RdoDisipador;
    private javax.swing.JRadioButton RdoFuente;
    private javax.swing.JRadioButton RdoHdd;
    private javax.swing.JRadioButton RdoPlaca;
    private javax.swing.JRadioButton RdoProcesador;
    private javax.swing.JRadioButton RdoRam;
    private javax.swing.JRadioButton RdoSsd;
    private javax.swing.JRadioButton RdoVentilador;
    private javax.swing.JScrollPane TblDatos;
    private javax.swing.JTextField TxtCantidad;
    private javax.swing.JTextField TxtCapacidad;
    private javax.swing.JTextField TxtIdPieza;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
