
package Visual;

import Controller.Sesion;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author jose9
 */
public class FrmPrincipal extends javax.swing.JFrame {

    Sesion ObjSesion = new Sesion();
    String tipoUsuario = ObjSesion.getTipoUsuario();
    public FrmPrincipal(String tipoUsuario) {
        
        this.setUndecorated(true);
        initComponents();
        Image icon = new ImageIcon(getClass().getResource("/Assets/Pollo (2).jpeg")).getImage();
        setIconImage(icon);
        try {
            java.awt.Taskbar.getTaskbar().setIconImage(icon);
        } catch (Exception e) {
        }
        setSize(700,609);
        setLocationRelativeTo(null);
        setResizable(false);

        configurarPorRol(tipoUsuario);
        
        LblMenuNombre.setText(ObjSesion.getNombreReal()+" "+ObjSesion.getApellidoReal());
        
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("ESCAPE"), "salir");
        getRootPane().getActionMap().put("salir", new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent e) {
            dispose();
            FrmLogin ObjLogin = new FrmLogin();
            ObjLogin.setVisible(true);
           }
        });
        
    }

    private FrmPrincipal() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    public void Salir(){
        int Opcion = JOptionPane.showConfirmDialog(this,"Esta seguro de salir?","Salir",0);
        if (Opcion == 0) {
            System.exit(0);
        }
    }
    

    
    public void configurarPorRol(String tipoUsuario) {
        tipoUsuario = tipoUsuario.toLowerCase();

        switch (tipoUsuario) {
            case "camionero":
                BtnCamioneros.setEnabled(true);
                BtnAdministrador.setEnabled(false);
                BtnMecanico.setEnabled(false);
                BtnRegistroEmpleados.setEnabled(false);
                BtnTecnico.setEnabled(false);
                break;

            case "mecanico":
                BtnCamioneros.setEnabled(false);
                BtnAdministrador.setEnabled(false);
                BtnMecanico.setEnabled(true);
                BtnRegistroEmpleados.setEnabled(false);
                BtnTecnico.setEnabled(false);
                break;
            case "administrador":
                BtnCamioneros.setEnabled(false);
                BtnAdministrador.setEnabled(true);
                BtnMecanico.setEnabled(false);
                BtnRegistroEmpleados.setEnabled(true);
                BtnTecnico.setEnabled(false);
                break;
            
            case "tecnico":
                BtnCamioneros.setEnabled(false);
                BtnAdministrador.setEnabled(false);
                BtnMecanico.setEnabled(false);
                BtnRegistroEmpleados.setEnabled(false);
                BtnTecnico.setEnabled(true);
                break;
                

            default:
                JOptionPane.showMessageDialog(this, "Tipo de usuario no reconocido");
                break;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LblMenu = new javax.swing.JLabel();
        LblInstrucciones = new javax.swing.JLabel();
        BtnCamioneros = new javax.swing.JButton();
        BtnAdministrador = new javax.swing.JButton();
        BtnMecanico = new javax.swing.JButton();
        LblLogo = new javax.swing.JLabel();
        LblMenuNombre = new javax.swing.JLabel();
        BtnRegistroEmpleados = new javax.swing.JButton();
        BtnTecnico = new javax.swing.JButton();
        BtnInventario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblMenu.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        LblMenu.setText("Bienvenido ");
        jPanel1.add(LblMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        LblInstrucciones.setText("Presione ESC o aqui para volver");
        LblInstrucciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblInstruccionesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblInstruccionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblInstruccionesMouseExited(evt);
            }
        });
        jPanel1.add(LblInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 539, 168, -1));

        BtnCamioneros.setText("Acceso Camioneros");
        BtnCamioneros.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnCamioneros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCamionerosActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCamioneros, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 192, -1));

        BtnAdministrador.setText("Acceso Administrador");
        BtnAdministrador.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdministradorActionPerformed(evt);
            }
        });
        jPanel1.add(BtnAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 192, -1));

        BtnMecanico.setText("Acceso Mecanico");
        BtnMecanico.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnMecanico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMecanicoActionPerformed(evt);
            }
        });
        jPanel1.add(BtnMecanico, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 192, -1));

        LblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Logo (1).jpeg"))); // NOI18N
        jPanel1.add(LblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        LblMenuNombre.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        LblMenuNombre.setText("Nombre");
        jPanel1.add(LblMenuNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 380, -1));

        BtnRegistroEmpleados.setText("Registrar nuevo empleado");
        BtnRegistroEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistroEmpleadosActionPerformed(evt);
            }
        });
        jPanel1.add(BtnRegistroEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 192, -1));

        BtnTecnico.setText("Mantenimiento de equipos");
        BtnTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTecnicoActionPerformed(evt);
            }
        });
        jPanel1.add(BtnTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 190, -1));

        BtnInventario.setText("Inventario de piezas");
        BtnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInventarioActionPerformed(evt);
            }
        });
        jPanel1.add(BtnInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 190, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 660, 570));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Pollo (2).jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LblInstruccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblInstruccionesMouseClicked
        dispose();
        FrmLogin ObjLogin = new FrmLogin();
        ObjLogin.setVisible(true);
               
    }//GEN-LAST:event_LblInstruccionesMouseClicked

    private void LblInstruccionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblInstruccionesMouseEntered
        LblInstrucciones.setForeground(Color.red);
    }//GEN-LAST:event_LblInstruccionesMouseEntered

    private void LblInstruccionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblInstruccionesMouseExited
        LblInstrucciones.setForeground(Color.black);
    }//GEN-LAST:event_LblInstruccionesMouseExited

    private void BtnCamionerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCamionerosActionPerformed
        dispose();
        FrmMecanico ObjMecanico = new FrmMecanico(tipoUsuario);
        ObjMecanico.setVisible(true);
        
    }//GEN-LAST:event_BtnCamionerosActionPerformed

    private void BtnAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdministradorActionPerformed
        //Admin
        dispose();
        FrmMecanico ObjMecanico = new FrmMecanico(tipoUsuario);
        ObjMecanico.setVisible(true);
    }//GEN-LAST:event_BtnAdministradorActionPerformed

    private void BtnMecanicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMecanicoActionPerformed
        //mecanico
        dispose();
        FrmMecanico ObjMecanico = new FrmMecanico(tipoUsuario);
        ObjMecanico.setVisible(true);       
    }//GEN-LAST:event_BtnMecanicoActionPerformed

    private void BtnRegistroEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistroEmpleadosActionPerformed
        //Admin
        dispose();
        FrmRegistro ObjRegistro = new FrmRegistro();
        ObjRegistro.setVisible(true);
    }//GEN-LAST:event_BtnRegistroEmpleadosActionPerformed

    private void BtnTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTecnicoActionPerformed
        dispose();
        FrmEquipos ObjEquipo = new FrmEquipos(tipoUsuario);
        ObjEquipo.setVisible(true);
    }//GEN-LAST:event_BtnTecnicoActionPerformed

    private void BtnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInventarioActionPerformed
        dispose();
        FrmInventario ObjInventario = new FrmInventario(tipoUsuario);
        ObjInventario.setVisible(true);
    }//GEN-LAST:event_BtnInventarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdministrador;
    private javax.swing.JButton BtnCamioneros;
    private javax.swing.JButton BtnInventario;
    private javax.swing.JButton BtnMecanico;
    private javax.swing.JButton BtnRegistroEmpleados;
    private javax.swing.JButton BtnTecnico;
    private javax.swing.JLabel LblInstrucciones;
    private javax.swing.JLabel LblLogo;
    public javax.swing.JLabel LblMenu;
    public javax.swing.JLabel LblMenuNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
