package Visual;
import Controller.CrudMantenimiento;
import Controller.Sesion;
import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import Controller.Detalles;
import Controller.ResultadoMantenimiento;
import javax.swing.JOptionPane;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.awt.Image;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jose9
 */
public class FrmEquipos extends javax.swing.JFrame {

    Sesion ObjSesion = new Sesion();
    CrudMantenimiento crud = new CrudMantenimiento();
    String tipoUsuario = ObjSesion.getTipoUsuario();
    public FrmEquipos(String tipoUsuario){
        this.setUndecorated(true);
        initComponents();
        Image icon = new ImageIcon(getClass().getResource("/Assets/Pollo (2).jpeg")).getImage();
        setIconImage(icon);
        try {
            java.awt.Taskbar.getTaskbar().setIconImage(icon);
        } catch (Exception e) {
        }
        setSize(850,697);
        setLocationRelativeTo(null);
        setResizable(false);
        
        TxtAreaMantenimiento.setEnabled(false);
        
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("ESCAPE"), "salir");
        getRootPane().getActionMap().put("salir", new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent e) {
            dispose();
            FrmPrincipal ObjPrincipal = new FrmPrincipal(tipoUsuario);
            ObjPrincipal .setVisible(true);
           }
        });
        
        TxtIdEquipo.addActionListener(e -> BtnBuscar.doClick());
    }

    private FrmEquipos() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void limpiarUi() {
        TxtAreaDetalle.setText("");

        ChkRam.setSelected(false);
        ChkProcesador.setSelected(false);
        ChkFuente.setSelected(false);
        ChkPlaca.setSelected(false);
        ChkDisipador.setSelected(false);
        ChkSsd.setSelected(false);
        ChkHdd.setSelected(false);

        ChkMonitor.setSelected(false);
        ChkMouse.setSelected(false);
        ChkTeclado.setSelected(false);

        BtngTipoMantenimiento.clearSelection();

        TxtAreaMantenimiento.setText("");
        TxtAreaDetalle.setText("");
    }
    
    private String ResumenDetalle(String idEquipo, Detalles d, java.sql.Date fecha, java.sql.Time hora) {

        StringBuilder sb = new StringBuilder();

        sb.append("=== MANTENIMIENTO DE EQUIPO ===\n\n");

        sb.append("ID Equipo: ").append(idEquipo).append("\n");
        sb.append("Tipo de mantenimiento: ")
          .append(d.tipoMantenimiento != null ? d.tipoMantenimiento : "No especificado")
          .append("\n");
        SimpleDateFormat sdfFecha = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat fmtHora = new SimpleDateFormat("HH:mm:ss");
        sb.append("Fecha: ").append(sdfFecha.format(fecha)).append("\n");
        sb.append("Hora: ").append(fmtHora.format(hora)).append("\n\n");
        
        sb.append("Componentes intervenidos:\n");

        if (d.ram) sb.append("- RAM\n");
        if (d.procesador) sb.append("- Procesador\n");
        if (d.fuente) sb.append("- Fuente de poder\n");
        if (d.placaBase) sb.append("- Placa base\n");
        if (d.disipador) sb.append("- Disipador\n");

        if (d.almacenamiento != null) {
            if (d.almacenamiento.ssd) sb.append("- SSD\n");
            if (d.almacenamiento.hdd) sb.append("- HDD\n");
        }

        sb.append("\nPeriféricos:\n");

        if (d.perifericos != null) {
            if (d.perifericos.monitor) sb.append("- Monitor\n");
            if (d.perifericos.mouse) sb.append("- Mouse\n");
            if (d.perifericos.teclado) sb.append("- Teclado\n");
        }

        sb.append("\nDetalle:\n");
        sb.append(d.descripcion != null ? d.descripcion : "Sin descripción");

        return sb.toString();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtngTipoMantenimiento = new javax.swing.ButtonGroup();
        Panel = new javax.swing.JPanel();
        LblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TxtIdEquipo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        ChkRam = new javax.swing.JCheckBox();
        ChkProcesador = new javax.swing.JCheckBox();
        ChkPlaca = new javax.swing.JCheckBox();
        ChkFuente = new javax.swing.JCheckBox();
        ChkDisipador = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        ChkSsd = new javax.swing.JCheckBox();
        ChkHdd = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtAreaDetalle = new javax.swing.JTextArea();
        LblEspecificacion = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        ChkMonitor = new javax.swing.JCheckBox();
        ChkTeclado = new javax.swing.JCheckBox();
        ChkMouse = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        RdoPreventivo = new javax.swing.JRadioButton();
        RdoCorrectivo = new javax.swing.JRadioButton();
        BtnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtAreaMantenimiento = new javax.swing.JTextArea();
        LblInstrucciones = new javax.swing.JLabel();
        LblDetalleManteminiemto = new javax.swing.JLabel();
        BtnRegistroMantenimiento = new javax.swing.JButton();
        BtnActualizar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnLimpiar = new javax.swing.JButton();
        TxtFecha = new javax.swing.JTextField();
        LblFechaMantenimiento = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnuMenu = new javax.swing.JMenu();
        MnuIInventario = new javax.swing.JMenuItem();
        MnuIPrincipal = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel.setPreferredSize(new java.awt.Dimension(830, 650));

        LblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblTitulo.setText("Mantenimiento de equipos");

        jLabel1.setText("Id del equipo");

        TxtIdEquipo.setToolTipText("Escriba una id para buscar, registrar, etc..");
        TxtIdEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIdEquipoActionPerformed(evt);
            }
        });
        TxtIdEquipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtIdEquipoKeyTyped(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Componentes Reemplazados"));
        jPanel2.setToolTipText("");

        ChkRam.setText("Ram");
        ChkRam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkRamActionPerformed(evt);
            }
        });

        ChkProcesador.setText("Procesador");

        ChkPlaca.setText("Placa base");
        ChkPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkPlacaActionPerformed(evt);
            }
        });

        ChkFuente.setText("Fuente de poder");

        ChkDisipador.setText("Disipador");
        ChkDisipador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkDisipadorActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Almacenamiento"));

        ChkSsd.setText("SSD");

        ChkHdd.setText("HDD");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChkSsd, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChkHdd, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ChkSsd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChkHdd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TxtAreaDetalle.setColumns(20);
        TxtAreaDetalle.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        TxtAreaDetalle.setRows(5);
        TxtAreaDetalle.setToolTipText("Detalle del mantenimiento realizado");
        jScrollPane2.setViewportView(TxtAreaDetalle);

        LblEspecificacion.setText("Detalle");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Perifericos"));

        ChkMonitor.setText("Monitor");

        ChkTeclado.setText("Teclado");

        ChkMouse.setText("Mouse");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(ChkMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChkTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ChkMouse, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChkMonitor)
                    .addComponent(ChkTeclado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ChkMouse)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de mantenimieto"));

        BtngTipoMantenimiento.add(RdoPreventivo);
        RdoPreventivo.setText("Preventivo");

        BtngTipoMantenimiento.add(RdoCorrectivo);
        RdoCorrectivo.setText("Correctivo");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RdoPreventivo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RdoCorrectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RdoPreventivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RdoCorrectivo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblEspecificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ChkRam, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ChkFuente, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(ChkProcesador, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 72, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(ChkPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ChkDisipador, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChkRam)
                    .addComponent(ChkProcesador)
                    .addComponent(ChkFuente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChkPlaca)
                    .addComponent(ChkDisipador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblEspecificacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addContainerGap())
        );

        BtnBuscar.setText("Buscar");
        BtnBuscar.setToolTipText("requiere id y fecha para buscar");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        TxtAreaMantenimiento.setColumns(20);
        TxtAreaMantenimiento.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        TxtAreaMantenimiento.setRows(5);
        TxtAreaMantenimiento.setToolTipText("Aqui se muestra la informacion buscada");
        TxtAreaMantenimiento.setEnabled(false);
        jScrollPane1.setViewportView(TxtAreaMantenimiento);

        LblInstrucciones.setText("Presione ESC o aqui para volver");
        LblInstrucciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblInstruccionesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblInstruccionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblInstruccionesMouseExited(evt);
            }
        });

        LblDetalleManteminiemto.setText("Detalle del ultimo mantenimiento");

        BtnRegistroMantenimiento.setText("Registrar\n mantenimiento\n");
        BtnRegistroMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistroMantenimientoActionPerformed(evt);
            }
        });

        BtnActualizar.setText("Actualizar mantenimiento");
        BtnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActualizarActionPerformed(evt);
            }
        });

        BtnEliminar.setText("Borrar registro");
        BtnEliminar.setToolTipText("requiere id y fecha para borrar");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        BtnLimpiar.setText("Limpiar los campos");
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });

        TxtFecha.setToolTipText("Formato: yyyy-mm-dd");
        TxtFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtFechaKeyTyped(evt);
            }
        });

        LblFechaMantenimiento.setText("Fecha");

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(LblDetalleManteminiemto, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 168, Short.MAX_VALUE))
                                    .addComponent(jScrollPane1)))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(BtnRegistroMantenimiento)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnActualizar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(TxtIdEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LblFechaMantenimiento)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                                                .addComponent(TxtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(BtnBuscar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(BtnEliminar)
                                                .addGap(93, 93, 93)))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LblInstrucciones)
                .addGap(308, 308, 308))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(LblTitulo)
                .addGap(9, 9, 9)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(LblDetalleManteminiemto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(LblFechaMantenimiento))
                        .addGap(7, 7, 7)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtIdEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnBuscar)
                            .addComponent(BtnEliminar)
                            .addComponent(TxtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnRegistroMantenimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(BtnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(LblInstrucciones)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        MnuMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Menu-right-outline.png"))); // NOI18N
        MnuMenu.setText("Menu");
        MnuMenu.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
                MnuMenuMenuCanceled(evt);
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
                MnuMenuMenuDeselected(evt);
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                MnuMenuMenuSelected(evt);
            }
        });

        MnuIInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Blackvariant-Button-Ui-System-Folders-Alt-Utilities.24.png"))); // NOI18N
        MnuIInventario.setText("Inventario");
        MnuIInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuIInventarioActionPerformed(evt);
            }
        });
        MnuMenu.add(MnuIInventario);

        MnuIPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Graphicloads-100-Flat-Home.24.png"))); // NOI18N
        MnuIPrincipal.setText("jMenuItem2");
        MnuIPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuIPrincipalActionPerformed(evt);
            }
        });
        MnuMenu.add(MnuIPrincipal);

        jMenuBar1.add(MnuMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtIdEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIdEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIdEquipoActionPerformed

    private void ChkRamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkRamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChkRamActionPerformed

    private void ChkDisipadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkDisipadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChkDisipadorActionPerformed

    private void ChkPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChkPlacaActionPerformed

    private void LblInstruccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblInstruccionesMouseClicked
        dispose();
        FrmPrincipal ObjPrincipal = new FrmPrincipal(tipoUsuario);
        ObjPrincipal.setVisible(true);
        
    }//GEN-LAST:event_LblInstruccionesMouseClicked

    private void LblInstruccionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblInstruccionesMouseEntered
        LblInstrucciones.setForeground(Color.red);
    }//GEN-LAST:event_LblInstruccionesMouseEntered

    private void LblInstruccionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblInstruccionesMouseExited
        LblInstrucciones.setForeground(Color.black);
    }//GEN-LAST:event_LblInstruccionesMouseExited

    private void BtnRegistroMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistroMantenimientoActionPerformed
        if (TxtIdEquipo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingresa un ID de equipo");
            return;
        }
        
        Detalles detalles = new Detalles();

        detalles.ram = ChkRam.isSelected();
        detalles.procesador = ChkProcesador.isSelected();
        detalles.fuente = ChkFuente.isSelected();
        detalles.placaBase = ChkPlaca.isSelected();
        detalles.disipador = ChkDisipador.isSelected();

        Detalles.Almacenamiento alm = new Detalles.Almacenamiento();
        alm.ssd = ChkSsd.isSelected();
        alm.hdd = ChkHdd.isSelected();
        detalles.almacenamiento = alm;

        Detalles.Perifericos per = new Detalles.Perifericos();
        per.monitor = ChkMonitor.isSelected();
        per.mouse = ChkMouse.isSelected();
        per.teclado = ChkTeclado.isSelected();
        detalles.perifericos = per;
        

        if (RdoPreventivo.isSelected()) {
            detalles.tipoMantenimiento = "PREVENTIVO";
        } else if (RdoCorrectivo.isSelected()) {
            detalles.tipoMantenimiento = "CORRECTIVO";
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona tipo de mantenimiento");
            return;
        }

        detalles.descripcion = TxtAreaDetalle.getText();
        
        ObjectMapper mapper = new ObjectMapper();

        String json = "";
        try {
            json = mapper.writeValueAsString(detalles);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al generar JSON");
            return;
        }
        
        String idEquipo = TxtIdEquipo.getText();
        String fecha = TxtFecha.getText();
        java.sql.Date fechaFormat = java.sql.Date.valueOf(fecha);
        CrudMantenimiento crud = new CrudMantenimiento();
        crud.guardar(idEquipo, json, fechaFormat);
    }//GEN-LAST:event_BtnRegistroMantenimientoActionPerformed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        
        String idEquipo = TxtIdEquipo.getText();
        String fecha = TxtFecha.getText();
        java.sql.Date fechaFormat = java.sql.Date.valueOf(fecha);
        if (idEquipo.isEmpty()||fecha.isEmpty()) {
           JOptionPane.showMessageDialog(this, "Campo Id o Fecha Vacios");
           return;
        }

        try {
            ResultadoMantenimiento res = crud.buscar(idEquipo, fechaFormat);

            if (res == null || res.json == null || res.json.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No hay mantenimiento registrado");
                return;
            }

            ObjectMapper mapper = new ObjectMapper();
            Detalles d = mapper.readValue(res.json, Detalles.class);

            limpiarUi();

            // reconstrucción UI
            ChkRam.setSelected(d.ram);
            ChkProcesador.setSelected(d.procesador);
            ChkFuente.setSelected(d.fuente);
            ChkPlaca.setSelected(d.placaBase);
            ChkDisipador.setSelected(d.disipador);

            ChkSsd.setSelected(d.almacenamiento != null && d.almacenamiento.ssd);
            ChkHdd.setSelected(d.almacenamiento != null && d.almacenamiento.hdd);

            ChkMonitor.setSelected(d.perifericos != null && d.perifericos.monitor);
            ChkMouse.setSelected(d.perifericos != null && d.perifericos.mouse);
            ChkTeclado.setSelected(d.perifericos != null && d.perifericos.teclado);

            if ("PREVENTIVO".equalsIgnoreCase(d.tipoMantenimiento)) {
                RdoPreventivo.setSelected(true);
            } else if ("CORRECTIVO".equalsIgnoreCase(d.tipoMantenimiento)) {
                RdoCorrectivo.setSelected(true);
            }
            TxtAreaDetalle.setText(d.descripcion);

            TxtAreaMantenimiento.setText(ResumenDetalle(idEquipo, d, (Date) res.fecha, res.hora));

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al cargar mantenimiento");
        }
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void TxtIdEquipoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtIdEquipoKeyTyped
        char c = evt.getKeyChar();

        // Convertir a mayúscula automáticamente
        evt.setKeyChar(Character.toUpperCase(c));
    }//GEN-LAST:event_TxtIdEquipoKeyTyped

    private void BtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActualizarActionPerformed
        String idEquipo = TxtIdEquipo.getText();
        String fecha = TxtFecha.getText();
        if (idEquipo.isEmpty() || fecha.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Campo Id o Fecha vacios");
            return;
        }
        Detalles d = new Detalles();

        d.ram = ChkRam.isSelected();
        d.procesador = ChkProcesador.isSelected();
        d.fuente = ChkFuente.isSelected();
        d.placaBase = ChkPlaca.isSelected();
        d.disipador = ChkDisipador.isSelected();

        d.almacenamiento = new Detalles.Almacenamiento();
        d.almacenamiento.ssd = ChkSsd.isSelected();
        d.almacenamiento.hdd = ChkHdd.isSelected();

        d.perifericos = new Detalles.Perifericos();
        d.perifericos.monitor = ChkMonitor.isSelected();
        d.perifericos.mouse = ChkMouse.isSelected();
        d.perifericos.teclado = ChkTeclado.isSelected();

        if (RdoPreventivo.isSelected()) {
            d.tipoMantenimiento = "PREVENTIVO";
        } else if (RdoCorrectivo.isSelected()) {
            d.tipoMantenimiento = "CORRECTIVO";
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona tipo de mantenimiento");
            return;
        }

        d.descripcion = TxtAreaDetalle.getText();

        try {
            ObjectMapper mapper = new ObjectMapper();
            String json = mapper.writeValueAsString(d);
            java.sql.Date fechaFormat = java.sql.Date.valueOf(fecha);
            crud.actualizar(idEquipo, json, fechaFormat);
            
            ResultadoMantenimiento res = crud.buscar(idEquipo,fechaFormat);

            TxtAreaMantenimiento.setText(ResumenDetalle(idEquipo, d, (Date) res.fecha, res.hora));

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al actualizar mantenimiento");
        }
    }//GEN-LAST:event_BtnActualizarActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        String idEquipo = TxtIdEquipo.getText();
        String fecha = TxtFecha.getText();
        if (idEquipo.isEmpty()||fecha.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Campo Id o Fecha vacios");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
            this,
            "¿Estás seguro de eliminar el mantenimiento del equipo " + idEquipo + "?",
            "Confirmación",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        java.sql.Date fechaFormat = java.sql.Date.valueOf(fecha);
        CrudMantenimiento crud = new CrudMantenimiento();
        crud.eiliminar(idEquipo, fechaFormat);

        limpiarUi();
        TxtAreaMantenimiento.setText("");
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
        limpiarUi();
    }//GEN-LAST:event_BtnLimpiarActionPerformed

    private void TxtFechaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtFechaKeyTyped
        char c = evt.getKeyChar();
        String texto = TxtFecha.getText();

        // 1. Solo permitir números
        if (!Character.isDigit(c)) {
            evt.consume();
            return;
        }

        // 2. Limitar a 10 caracteres (yyyy-mm-dd)
        if (texto.length() >= 10) {
            evt.consume();
            return;
        }

        // 3. Insertar guiones automáticamente
        // Nota: El evento KeyTyped ocurre antes de que el caracter se añada al texto
        if (texto.length() == 4 || texto.length() == 7) {
            TxtFecha.setText(texto + "-");
        }    
    }//GEN-LAST:event_TxtFechaKeyTyped

    private void MnuIInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuIInventarioActionPerformed
        dispose();
        FrmInventario ObjInventario = new FrmInventario(tipoUsuario);
        ObjInventario.setVisible(true);     
    }//GEN-LAST:event_MnuIInventarioActionPerformed

    private void MnuIPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuIPrincipalActionPerformed
        dispose();
        FrmPrincipal ObjPrincipal = new FrmPrincipal(tipoUsuario);
        ObjPrincipal .setVisible(true);
    }//GEN-LAST:event_MnuIPrincipalActionPerformed

    private void MnuMenuMenuCanceled(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_MnuMenuMenuCanceled
       MnuMenu.setIcon(new ImageIcon(getClass().getResource("/Assets/Menu-right-outline.png")));
    }//GEN-LAST:event_MnuMenuMenuCanceled

    private void MnuMenuMenuDeselected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_MnuMenuMenuDeselected
       MnuMenu.setIcon(new ImageIcon(getClass().getResource("/Assets/Menu-right-outline.png")));
    }//GEN-LAST:event_MnuMenuMenuDeselected

    private void MnuMenuMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_MnuMenuMenuSelected
        MnuMenu.setIcon(new ImageIcon(getClass().getResource("/Assets/Menu-down-outline.png")));
    }//GEN-LAST:event_MnuMenuMenuSelected
                                  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEquipos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizar;
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JButton BtnRegistroMantenimiento;
    private javax.swing.ButtonGroup BtngTipoMantenimiento;
    private javax.swing.JCheckBox ChkDisipador;
    private javax.swing.JCheckBox ChkFuente;
    private javax.swing.JCheckBox ChkHdd;
    private javax.swing.JCheckBox ChkMonitor;
    private javax.swing.JCheckBox ChkMouse;
    private javax.swing.JCheckBox ChkPlaca;
    private javax.swing.JCheckBox ChkProcesador;
    private javax.swing.JCheckBox ChkRam;
    private javax.swing.JCheckBox ChkSsd;
    private javax.swing.JCheckBox ChkTeclado;
    private javax.swing.JLabel LblDetalleManteminiemto;
    private javax.swing.JLabel LblEspecificacion;
    private javax.swing.JLabel LblFechaMantenimiento;
    private javax.swing.JLabel LblInstrucciones;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JMenuItem MnuIInventario;
    private javax.swing.JMenuItem MnuIPrincipal;
    private javax.swing.JMenu MnuMenu;
    private javax.swing.JPanel Panel;
    private javax.swing.JRadioButton RdoCorrectivo;
    private javax.swing.JRadioButton RdoPreventivo;
    private javax.swing.JTextArea TxtAreaDetalle;
    private javax.swing.JTextArea TxtAreaMantenimiento;
    private javax.swing.JTextField TxtFecha;
    private javax.swing.JTextField TxtIdEquipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
