
package Visual;

import Controller.BloqueoController;
import Controller.ControladoresGenericos;
import Controller.Login;
import Controller.Sesion;
import Modelo.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

import java.sql.ResultSet;
import java.time.Duration;
import java.time.LocalDateTime;
import java.util.HashSet;
import javax.swing.ImageIcon;


/**
 *
 * @author jose9
 */
public class FrmLogin extends javax.swing.JFrame {
    
    private static int Intentos = 0;
    private static LocalDateTime horaBloqueo = null;
    Sesion ObjSesion = new Sesion();
    BloqueoController bloqueoCtrl = new BloqueoController();
    Conexion con = new Conexion();
    Login ObjLogin = new Login();
    
    public FrmLogin() {
        this.setUndecorated(true);
        initComponents();
        Image icon = new ImageIcon(getClass().getResource("/Assets/Pollo (2).jpeg")).getImage();
        setIconImage(icon);
        try {
            java.awt.Taskbar.getTaskbar().setIconImage(icon);
        } catch (Exception e) {
        }
        
        setSize(400,579);
        setLocationRelativeTo(null);
        setResizable(false);
        
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("ESCAPE"), "salir");
        getRootPane().getActionMap().put("salir", new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent e) {
            Salir();
           }
        });
        TxtUsuario.addActionListener(e -> BtnIngresar.doClick());
        TxtClave.addActionListener(e -> BtnIngresar.doClick());
        
    }
    
    public void Salir(){
        int Opcion = JOptionPane.showConfirmDialog(this,"Esta seguro de salir?","Salir",0);
        if (Opcion == 0) {
            System.exit(0);
        }
    }
    
    public boolean Bloqueo(){
        
        // Si el sistema está bloqueado, verificamos si ya pasaron los 5 minutos
        if (horaBloqueo != null) {
            LocalDateTime ahora = LocalDateTime.now();
            Duration diferencia = Duration.between(horaBloqueo, ahora);

            if (diferencia.toMinutes() < 5) {
                long minutosRestantes = 5 - diferencia.toMinutes();
                JOptionPane.showMessageDialog(this, 
                    "El sistema está bloqueado. Intenta de nuevo en " + minutosRestantes + " minuto(s).",
                    "BLOQUEADO", JOptionPane.WARNING_MESSAGE);
                return true; // no deja continuar
            } else {
                // Ya pasaron los 5 minutos, se resetea el bloqueo
                horaBloqueo = null;
                Intentos = 0;
                return false;
            }
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LblUsuario = new javax.swing.JLabel();
        TxtUsuario = new javax.swing.JTextField();
        LblContrasena = new javax.swing.JLabel();
        TxtClave = new javax.swing.JTextField();
        BtnIngresar = new javax.swing.JButton();
        LblInstrucciones = new javax.swing.JLabel();
        LblLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblUsuario.setText("Usuario");

        TxtUsuario.setToolTipText("Formato\nXX.XXX.XXX-X");
        TxtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUsuarioActionPerformed(evt);
            }
        });
        TxtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtUsuarioKeyTyped(evt);
            }
        });

        LblContrasena.setText("Contraseña");

        TxtClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtClaveActionPerformed(evt);
            }
        });

        BtnIngresar.setText("Ingresar");
        BtnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIngresarActionPerformed(evt);
            }
        });

        LblInstrucciones.setText("Presione ESC o aqui para salir");
        LblInstrucciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblInstruccionesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblInstruccionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblInstruccionesMouseExited(evt);
            }
        });

        LblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Logo (1).jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtUsuario)
                            .addComponent(LblContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtClave, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(LblInstrucciones))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(BtnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(LblLogo)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(LblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LblUsuario)
                .addGap(18, 18, 18)
                .addComponent(TxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LblContrasena)
                .addGap(18, 18, 18)
                .addComponent(TxtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(LblInstrucciones)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Pollo (2).jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUsuarioActionPerformed

    private void TxtClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtClaveActionPerformed

    private void LblInstruccionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblInstruccionesMouseEntered
        LblInstrucciones.setForeground(Color.red);
    }//GEN-LAST:event_LblInstruccionesMouseEntered

    private void LblInstruccionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblInstruccionesMouseExited
       LblInstrucciones.setForeground(Color.black);
    }//GEN-LAST:event_LblInstruccionesMouseExited

    private void LblInstruccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblInstruccionesMouseClicked
        Salir();
    }//GEN-LAST:event_LblInstruccionesMouseClicked

    private void BtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresarActionPerformed
        
       
        // Verificar si el equipo está bloqueado
        if (bloqueoCtrl.verificarBloqueo()) {
            JOptionPane.showMessageDialog(this, "Este equipo está bloqueado temporalmente.\n" +"Intente nuevamente después de 5 minutos.","BLOQUEADO", JOptionPane.ERROR_MESSAGE);
            return;
        }

        

        String usuario = TxtUsuario.getText();
        String clave = TxtClave.getText();

        try {
            
            ResultSet resultadoLogin = ObjLogin.ValidarUsuario(usuario, clave);

            if (resultadoLogin == null) {
                JOptionPane.showMessageDialog(this, "No hay conexión", "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (resultadoLogin.next()) {
                /*String tipoUsuario = resultadoLogin.getString("userType");
                String nombreReal = resultadoLogin.getString("realName");*/
                ObjSesion.setNombreReal(resultadoLogin.getString("Nombre"));
                ObjSesion.setApellidoReal(resultadoLogin.getString("Apellido"));
                ObjSesion.setTipoUsuario(resultadoLogin.getString("Cargo"));
                ObjSesion.setIdCamion(resultadoLogin.getString("idCamion"));
                FrmPrincipal ObjPrincipal = new FrmPrincipal(ObjSesion.getTipoUsuario());
                ObjPrincipal.setVisible(true);
               
                Intentos = 0;
                dispose();
            } else {
                Intentos++;
                JOptionPane.showMessageDialog(this, "Contraseña o usuario inválido", "ERROR", JOptionPane.ERROR_MESSAGE);

                if (Intentos >= 3) {
                    bloqueoCtrl.activarBloqueo();
                    JOptionPane.showMessageDialog(this,
                            "Demasiados intentos fallidos.\nEl equipo ha sido bloqueado por 5 minutos.",
                            "BLOQUEADO", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnIngresarActionPerformed

    private void TxtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtUsuarioKeyTyped
        ControladoresGenericos.manejarRut(TxtUsuario, evt);
    }//GEN-LAST:event_TxtUsuarioKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIngresar;
    private javax.swing.JLabel LblContrasena;
    private javax.swing.JLabel LblInstrucciones;
    private javax.swing.JLabel LblLogo;
    private javax.swing.JLabel LblUsuario;
    private javax.swing.JTextField TxtClave;
    private javax.swing.JTextField TxtUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
