/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Visual;

import Controller.ControladoresGenericos;
import Controller.CrudCamiones;
import Controller.Sesion;
import Modelo.Conexion;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.AbstractAction;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;
import Generics.Camion;
/**
 *
 * @author jose9
 */
public class FrmMecanico extends javax.swing.JFrame {

    Sesion ObjSesion = new Sesion();
    CrudCamiones CamionesCrud = new CrudCamiones();
    String tipoUsuario = ObjSesion.getTipoUsuario();
    Camion c = new Camion();
    public FrmMecanico(String tipoUsuario) {

        this.setUndecorated(true);
        initComponents();
        Image icon = new ImageIcon(getClass().getResource("/Assets/Pollo (2).jpeg")).getImage();
        setIconImage(icon);
        try {
            java.awt.Taskbar.getTaskbar().setIconImage(icon);
        } catch (Exception e) {
        }
        setSize(965, 498);
        setLocationRelativeTo(null);
        setResizable(false);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/question-faq-icon.png")));
        MostrarDatosTabla();
        ConfigurarUsuario(tipoUsuario);
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("ESCAPE"), "salir");
        getRootPane().getActionMap().put("salir", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                FrmPrincipal ObjPrincipal = new FrmPrincipal(ObjSesion.getTipoUsuario());
                ObjPrincipal.setVisible(true);
            }
        });
        
        TxtPatente.addActionListener(e -> BtnBuscar.doClick());

    }

    private FrmMecanico() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    private void validarKilometraje(int km) {

    if (km > 0 && km % 5000 == 0) {
        
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Close-2-icon.png")));

        JOptionPane.showMessageDialog(this, 
            "Este camión requiere mantenimiento (KM: " + km + ")", 
            "ALERTA", 
            JOptionPane.WARNING_MESSAGE);

    } else {
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Ok-icon.png")));
    }
    }

    public void ConfigurarUsuario(String tipoUsuario) {

        switch (tipoUsuario.toLowerCase()) {
            case "mecanico":
                BtnModificar.setEnabled(true);
                BtnModificar.setText("Actualizar KM");
                BtnEliminar.setEnabled(false);
                BtnRegistrar.setEnabled(false);

                TxtMarca.setEnabled(false);
                TxtModelo.setEnabled(false);
                TxtAnio.setEnabled(false);
                break;

            case "administrador":
                BtnModificar.setEnabled(true);
                BtnModificar.setText("Actualizar");
                BtnEliminar.setEnabled(true);
                BtnRegistrar.setEnabled(true);

                TxtMarca.setEnabled(true);
                TxtModelo.setEnabled(true);
                TxtAnio.setEnabled(true);
                break;
                            
            case "super admin":
                BtnModificar.setEnabled(true);
                BtnModificar.setText("Actualizar KM");
                BtnEliminar.setEnabled(true);
                BtnRegistrar.setEnabled(true);

                TxtMarca.setEnabled(true);
                TxtModelo.setEnabled(true);
                TxtAnio.setEnabled(true);
                break;

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LblTitulo = new javax.swing.JLabel();
        LblMarca = new javax.swing.JLabel();
        TxtMarca = new javax.swing.JTextField();
        LblModelo = new javax.swing.JLabel();
        TxtModelo = new javax.swing.JTextField();
        LblContraseña = new javax.swing.JLabel();
        LblTipoUsuario = new javax.swing.JLabel();
        CmbEstado = new javax.swing.JComboBox<>();
        LblTotalUsuarios = new javax.swing.JLabel();
        BtnRegistrar = new javax.swing.JButton();
        BtnVolver = new javax.swing.JButton();
        TxtAnio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblDatos = new javax.swing.JTable();
        LblRut = new javax.swing.JLabel();
        TxtPatente = new javax.swing.JTextField();
        BtnBuscar = new javax.swing.JButton();
        BtnModificar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnLimpiar = new javax.swing.JButton();
        BtnRecarga = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TxtKilometraje = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblTitulo.setText("Mecanico");

        LblMarca.setText("Marca");

        TxtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtMarcaActionPerformed(evt);
            }
        });
        TxtMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtMarcaKeyTyped(evt);
            }
        });

        LblModelo.setText("Modelo");

        TxtModelo.setToolTipText("");
        TxtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtModeloActionPerformed(evt);
            }
        });
        TxtModelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtModeloKeyTyped(evt);
            }
        });

        LblContraseña.setText("Año");

        LblTipoUsuario.setText("Estado");

        CmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OPERATIVO", "MANTENIMIENTO" }));
        CmbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbEstadoActionPerformed(evt);
            }
        });

        LblTotalUsuarios.setText("Total camiones : ¿?");

        BtnRegistrar.setText("Registrar");
        BtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarActionPerformed(evt);
            }
        });

        BtnVolver.setText("Volver");
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });

        TxtAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtAnioActionPerformed(evt);
            }
        });
        TxtAnio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtAnioKeyTyped(evt);
            }
        });

        TblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TblDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblDatos);

        LblRut.setText("Patente");

        TxtPatente.setToolTipText("Escriba una patente para buscar, registrar, etc...");
        TxtPatente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPatenteActionPerformed(evt);
            }
        });
        TxtPatente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPatenteKeyTyped(evt);
            }
        });

        BtnBuscar.setText("Buscar");
        BtnBuscar.setToolTipText("");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        BtnModificar.setText("Modificar");
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });

        BtnEliminar.setText("Eliminar");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        BtnLimpiar.setText("Limpiar campos");
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });

        BtnRecarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/refresh-page-option.png"))); // NOI18N
        BtnRecarga.setText("Recargar datos");
        BtnRecarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRecargaActionPerformed(evt);
            }
        });

        jLabel1.setText("Kilometraje");

        TxtKilometraje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtKilometrajeActionPerformed(evt);
            }
        });
        TxtKilometraje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtKilometrajeKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(426, 426, 426)
                        .addComponent(LblTotalUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(400, 400, 400)
                                .addComponent(BtnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(LblTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(CmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BtnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnRecarga, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TxtKilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(TxtPatente)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(BtnBuscar)
                                            .addGap(64, 64, 64))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(TxtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(LblMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(TxtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(LblModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(LblRut, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LblTitulo)
                        .addGap(33, 33, 33)
                        .addComponent(LblRut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnBuscar)
                            .addComponent(TxtPatente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblMarca)
                            .addComponent(LblModelo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtModelo))
                        .addGap(28, 28, 28)
                        .addComponent(LblContraseña)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LblTotalUsuarios)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BtnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(BtnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(BtnRegistrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnRecarga, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtKilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblTipoUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 510));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Pollo (2).jpeg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private String safe(Object valor) {
        return valor == null ? "" : valor.toString();
    }

    public void MostrarDatosTabla() {
        DefaultTableModel ObjModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        ObjModel.addColumn("Patente");
        ObjModel.addColumn("Marca");
        ObjModel.addColumn("Modelo");
        ObjModel.addColumn("Año");
        ObjModel.addColumn("Kilometraje");
        ObjModel.addColumn("Estado");

        TblDatos.setModel(ObjModel);

        ResultSet resultado = null;
        Connection con = null;
        try {
            resultado = CamionesCrud.listatTodos();
            if (resultado != null) {
                con = resultado.getStatement().getConnection();

            }

            int cantRegistros = 0;
            while (resultado != null && resultado.next()) {
                ObjModel.addRow(new Object[]{
                    resultado.getString("idCamion"),
                    resultado.getString("marca"),
                    resultado.getString("modelo"),
                    resultado.getString("anio"),
                    resultado.getString("kilometrajeActual"),
                    resultado.getString("estadoMantenimiento"),});

                cantRegistros++;

            }

            LblTotalUsuarios.setText("Total Camiones: " + cantRegistros);

        } catch (SQLException e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(this, "No se pudieron cargar los datos", "Alerta", JOptionPane.WARNING_MESSAGE);
        }

    }

    private void TxtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtModeloActionPerformed

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed

        dispose();
        FrmPrincipal ObjPrincipal = new FrmPrincipal(ObjSesion.getTipoUsuario());
        ObjPrincipal.setVisible(true);
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void BtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarActionPerformed

        DlgVerificacion dlg = new DlgVerificacion(this, true, tipoUsuario);
        dlg.setVisible(true);
        
        if(dlg.isVerificado()){
            int KM;
            String Patente = TxtPatente.getText();
            //String dv = TxtVerificador.getText();
            String Marca = TxtMarca.getText();
            String Modelo = TxtModelo.getText().trim();
            String AnioTxt = TxtAnio.getText();
            String KmTxt = TxtKilometraje.getText();

            if (KmTxt.isEmpty()) {
                KM = 0;
            } else {
                KM = Integer.parseInt(KmTxt);
                
            }

            int Anio = Integer.parseInt(AnioTxt);
            String Estado = (String) CmbEstado.getSelectedItem();

            //String idCamion = (String)CmbCamiones.getSelectedItem();
            if (Patente.isEmpty() || Marca.isEmpty() || Modelo.isEmpty() || AnioTxt.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Faltan campos por completar", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }
            c.setIdCamion(Patente);
            c.setMarca(Marca);
            c.setModelo(Modelo);
            c.setAnio(Anio);
            c.setKilometrajeActual(KM);
            c.setEstadoMantenimiento(Estado);
            
            CamionesCrud.grabar(c);
            MostrarDatosTabla();
            
            validarKilometraje(KM);
 
        }else {
            JOptionPane.showMessageDialog(this, "Accion Cancelada","Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BtnRegistrarActionPerformed

    private void CmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbEstadoActionPerformed

    private void TblDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblDatosMouseClicked
        int filaSeleccionada = TblDatos.rowAtPoint(evt.getPoint());

        TxtPatente.setText(safe(TblDatos.getValueAt(filaSeleccionada, 0)));
        TxtMarca.setText(safe(TblDatos.getValueAt(filaSeleccionada, 1)));
        TxtModelo.setText(safe(TblDatos.getValueAt(filaSeleccionada, 2)));
        TxtAnio.setText(safe(TblDatos.getValueAt(filaSeleccionada, 3)));
        TxtKilometraje.setText(safe(TblDatos.getValueAt(filaSeleccionada, 4)));

        CmbEstado.setSelectedItem(safe(TblDatos.getValueAt(filaSeleccionada, 5)));
        
        try {
        int km = Integer.parseInt(safe(TblDatos.getValueAt(filaSeleccionada, 4)));
            validarKilometraje(km);
        } catch (Exception e) {
            System.out.println("Error al convertir KM");
        }
    }//GEN-LAST:event_TblDatosMouseClicked

    private void TxtPatenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPatenteActionPerformed

    }//GEN-LAST:event_TxtPatenteActionPerformed

    private void TxtPatenteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPatenteKeyTyped
        char c = evt.getKeyChar();

        // Convertir a mayúscula automáticamente
        evt.setKeyChar(Character.toUpperCase(c));

        // Permitir solo letras, números y guion
        if (!Character.isLetterOrDigit(c) && c != '-') {
            evt.consume(); // bloquea el caracter
        }
    }//GEN-LAST:event_TxtPatenteKeyTyped

    //modificar campos para buscar
    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        String Patente = TxtPatente.getText();
        if (Patente.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingresa una patente para buscar", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            Camion c = CamionesCrud.buscar(Patente);
            if (c != null) {
                TxtPatente.setText(c.getIdCamion());
                TxtMarca.setText(c.getMarca());
                TxtModelo.setText(c.getModelo());
                TxtAnio.setText(Integer.toString(c.getAnio()));
                TxtKilometraje.setText(Integer.toString(c.getKilometrajeActual()));
                CmbEstado.setSelectedItem(c.getEstadoMantenimiento());

            } else {
                JOptionPane.showMessageDialog(null, "Camion no encontrado", "Advertencia", JOptionPane.WARNING_MESSAGE);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Faltan campos por completar", "Advertencia", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
 
            
        String Patente = TxtPatente.getText();
        if (Patente.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor ingresa una patente", "Alert", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String Marca = TxtMarca.getText();
        String Modelo = TxtModelo.getText();
        String AnioText = TxtAnio.getText();
        String Estado = (String) CmbEstado.getSelectedItem();
        String KilometrajeText = TxtKilometraje.getText();

        if (KilometrajeText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Faltan campos por completar", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        } 
        
        if ("Administrador".equalsIgnoreCase(tipoUsuario)) {
            if (Marca.isEmpty() || Modelo.isEmpty() || AnioText.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Faltan campos por completar", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
    
        int Kilometraje = Integer.parseInt(KilometrajeText);
        int Anio = Integer.parseInt(AnioText);


        if ("Administrador".equalsIgnoreCase(tipoUsuario)) {

            DlgVerificacion dlg = new DlgVerificacion(this, true, tipoUsuario);
            dlg.setVisible(true);

            if (!dlg.isVerificado()) {
                JOptionPane.showMessageDialog(this, "Verificación cancelada");
                return;
            }
        }
        c.setIdCamion(Patente);
        c.setMarca(Marca);
        c.setModelo(Modelo);
        c.setAnio(Anio);
        c.setKilometrajeActual(Kilometraje);
        c.setEstadoMantenimiento(Estado);

        CamionesCrud.actualizar(c);
        MostrarDatosTabla();
        validarKilometraje(Kilometraje);

    }//GEN-LAST:event_BtnModificarActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        
        DlgVerificacion dlg = new DlgVerificacion(this, true, tipoUsuario);
        dlg.setVisible(true);
        
        if(dlg.isVerificado()){
            String id = TxtPatente.getText();
            if (id.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Ingresa un rut para eliminar", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            int Confirm = JOptionPane.showConfirmDialog(this, "Estas seguro de eliminar a este Empleado?", "Confirmacion", JOptionPane.YES_NO_OPTION);

            if (Confirm == JOptionPane.YES_OPTION) {
                CamionesCrud.eiliminar(id);

            }
            MostrarDatosTabla();
        }else {
            JOptionPane.showMessageDialog(this, "Accion Cancelada","Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
        TxtPatente.setText(null);
        TxtModelo.setText(null);
        TxtAnio.setText(null);
        TxtMarca.setText(null);
        TxtKilometraje.setText(null);
        CmbEstado.setSelectedIndex(0);

    }//GEN-LAST:event_BtnLimpiarActionPerformed

    private void BtnRecargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRecargaActionPerformed
        MostrarDatosTabla();
    }//GEN-LAST:event_BtnRecargaActionPerformed

    private void TxtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtMarcaActionPerformed

    private void TxtAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAnioActionPerformed

    private void TxtKilometrajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtKilometrajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtKilometrajeActionPerformed

    private void TxtAnioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtAnioKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            evt.consume();
        }       
    }//GEN-LAST:event_TxtAnioKeyTyped

    private void TxtKilometrajeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtKilometrajeKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_TxtKilometrajeKeyTyped

    private void TxtMarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtMarcaKeyTyped
        char c = evt.getKeyChar();

        evt.setKeyChar(Character.toUpperCase(c));

        if (!Character.isLetterOrDigit(c) && c != ' ' && c != '-') {
            evt.consume();
        }

    }//GEN-LAST:event_TxtMarcaKeyTyped

    private void TxtModeloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtModeloKeyTyped
        char c = evt.getKeyChar();

        evt.setKeyChar(Character.toUpperCase(c));

        if (!Character.isLetterOrDigit(c) && c != ' ' && c != '-') {
            evt.consume();
        }       
    }//GEN-LAST:event_TxtModeloKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMecanico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JButton BtnRecarga;
    private javax.swing.JButton BtnRegistrar;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JComboBox<String> CmbEstado;
    private javax.swing.JLabel LblContraseña;
    private javax.swing.JLabel LblMarca;
    private javax.swing.JLabel LblModelo;
    private javax.swing.JLabel LblRut;
    private javax.swing.JLabel LblTipoUsuario;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JLabel LblTotalUsuarios;
    private javax.swing.JTable TblDatos;
    private javax.swing.JTextField TxtAnio;
    private javax.swing.JTextField TxtKilometraje;
    private javax.swing.JTextField TxtMarca;
    private javax.swing.JTextField TxtModelo;
    private javax.swing.JTextField TxtPatente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
    

}
