/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Visual;

import Controller.ControladoresGenericos;
import Controller.CrudUsuarios;
import Controller.Sesion;
import Generics.Usuario;
import Modelo.Conexion;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.AbstractAction;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jose9
 */
public class FrmRegistro extends javax.swing.JFrame {
    

    Sesion ObjSesion = new Sesion();
    CrudUsuarios UsuariosCrud = new CrudUsuarios();
    Usuario u = new Usuario();
    String tipoUsuarioOriginal;
    public FrmRegistro(){
        this.setUndecorated(true);
        initComponents();
        Image icon = new ImageIcon(getClass().getResource("/Assets/Pollo (2).jpeg")).getImage();
        setIconImage(icon);
        try {
            java.awt.Taskbar.getTaskbar().setIconImage(icon);
        } catch (Exception e) {
        }
        setSize(965,498);
        setLocationRelativeTo(null);
        setResizable(false);
        
        cargarCamiones();
        MostrarDatosTabla();
        
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("ESCAPE"), "salir");
        getRootPane().getActionMap().put("salir", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                FrmPrincipal ObjPrincipal = new FrmPrincipal(ObjSesion.getTipoUsuario());
                ObjPrincipal.setVisible(true);
            }
        });
        
        TxtRut.addActionListener(e -> BtnBuscar.doClick());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LblTitulo = new javax.swing.JLabel();
        LblNombre = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        LblApellido = new javax.swing.JLabel();
        TxtApellido = new javax.swing.JTextField();
        LblContraseña = new javax.swing.JLabel();
        LblTipoUsuario = new javax.swing.JLabel();
        CmbTipoUsuario = new javax.swing.JComboBox<>();
        LblTotalUsuarios = new javax.swing.JLabel();
        BtnRegistrar = new javax.swing.JButton();
        BtnVolver = new javax.swing.JButton();
        TxtClave = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblDatos = new javax.swing.JTable();
        LblRut = new javax.swing.JLabel();
        TxtRut = new javax.swing.JTextField();
        BtnBuscar = new javax.swing.JButton();
        BtnModificar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnLimpiar = new javax.swing.JButton();
        BtnRecarga = new javax.swing.JButton();
        LblCamiones = new javax.swing.JLabel();
        CmbCamiones = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblTitulo.setText("Registro de Usuarios");

        LblNombre.setText("Nombre");

        TxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreActionPerformed(evt);
            }
        });

        LblApellido.setText("Apellido");

        TxtApellido.setToolTipText("");
        TxtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtApellidoActionPerformed(evt);
            }
        });

        LblContraseña.setText("Contraseña");

        LblTipoUsuario.setText("Tipo Usuario");

        CmbTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Camionero", "Mecanico", "Administrador" }));
        CmbTipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbTipoUsuarioActionPerformed(evt);
            }
        });

        LblTotalUsuarios.setText("Total usuarios : ¿?");

        BtnRegistrar.setText("Registrar");
        BtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarActionPerformed(evt);
            }
        });

        BtnVolver.setText("Volver");
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });

        TblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TblDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblDatos);

        LblRut.setText("Rut");

        TxtRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRutActionPerformed(evt);
            }
        });
        TxtRut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtRutKeyTyped(evt);
            }
        });

        BtnBuscar.setText("Buscar");
        BtnBuscar.setToolTipText("");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        BtnModificar.setText("Modificar");
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });

        BtnEliminar.setText("Eliminar");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        BtnLimpiar.setText("Limpiar campos");
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });

        BtnRecarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/refresh-page-option.png"))); // NOI18N
        BtnRecarga.setText("Recargar datos");
        BtnRecarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRecargaActionPerformed(evt);
            }
        });

        LblCamiones.setText("Patente camiones");

        CmbCamiones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        CmbCamiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbCamionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(LblTotalUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtClave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LblRut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(TxtRut)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(BtnBuscar))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(LblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(LblApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(TxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LblTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CmbTipoUsuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LblCamiones, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CmbCamiones, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(BtnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnRecarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(17, 17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LblTitulo)
                        .addGap(33, 33, 33)
                        .addComponent(LblRut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnBuscar)
                            .addComponent(TxtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblNombre)
                            .addComponent(LblApellido))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtApellido))
                        .addGap(28, 28, 28)
                        .addComponent(LblContraseña)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LblTotalUsuarios)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnRecarga, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LblTipoUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CmbTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(LblCamiones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CmbCamiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        BtnRegistrar.getAccessibleContext().setAccessibleName("");
        BtnVolver.getAccessibleContext().setAccessibleName("");
        BtnModificar.getAccessibleContext().setAccessibleName("");
        BtnEliminar.getAccessibleContext().setAccessibleName("");
        BtnLimpiar.getAccessibleContext().setAccessibleName("");
        BtnRecarga.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private String safe(Object valor){
        return valor == null ? "" : valor.toString();
    }
    
    public void cargarCamiones() {
        CmbCamiones.removeAllItems();

        try {
            ResultSet resultado = UsuariosCrud.listarCamiones();

            // equivalente a NULL
            CmbCamiones.addItem("Sin camion asignado");

            while (resultado != null && resultado.next()) {
                String idCamion = resultado.getString("idCamion");
                CmbCamiones.addItem(idCamion);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar camiones");
        }
    }

    
     public void MostrarDatosTabla(){
        DefaultTableModel ObjModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        
        ObjModel.addColumn("Rut");
        ObjModel.addColumn("Clave");
        ObjModel.addColumn("Nombre");
        ObjModel.addColumn("Apellido");
        ObjModel.addColumn("idCamion");
        ObjModel.addColumn("Cargo");
        
        TblDatos.setModel(ObjModel);
        
        ResultSet resultado = null;
        Connection con = null;
        try {
            resultado = UsuariosCrud.listatTodos();
            if (resultado != null) {
                con = resultado.getStatement().getConnection();
                
            }
            
            int cantRegistros = 0;
            while (resultado != null && resultado.next()) {
                ObjModel.addRow(new Object[]{
                resultado.getString("Rut"),
                resultado.getString("Contrasena"),
                resultado.getString("Nombre"),
                resultado.getString("Apellido"),
                resultado.getString("idCamion"),
                resultado.getString("Cargo"),
                
                });
                
                cantRegistros ++;
                
            }
     
           LblTotalUsuarios.setText("Total usuarios: "+cantRegistros);
                
           
            
            
        } catch (SQLException e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,"No se pudieron cargar los datos","Alerta", JOptionPane.WARNING_MESSAGE);
        }
                
    }
     
    private void TxtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtApellidoActionPerformed

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
       
       dispose();
       FrmPrincipal ObjPrincipal = new FrmPrincipal(ObjSesion.getTipoUsuario());
       ObjPrincipal.setVisible(true);
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void BtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarActionPerformed
        String Rut = TxtRut.getText();
        //String dv = TxtVerificador.getText();
        String Nombre = TxtNombre.getText();
        String Apellido = TxtApellido.getText().trim();
        String Clave = TxtClave.getText();

        String TipoUsuario = (String)CmbTipoUsuario.getSelectedItem();
        String idCamion = (String)CmbCamiones.getSelectedItem();
        if(Rut.isEmpty()||Nombre.isEmpty() || Apellido.isEmpty() || Clave.isEmpty() ){
            JOptionPane.showMessageDialog(null,"Faltan campos por completar","Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        u.setRut(Rut);
        u.setNombre(Nombre);
        u.setApellido(Apellido);
        u.setClave(Clave);
        u.setIdCamion(idCamion);
        u.setTipoUsuario(TipoUsuario);
        
        UsuariosCrud.grabar(u);
        MostrarDatosTabla();
    }//GEN-LAST:event_BtnRegistrarActionPerformed

    private void CmbTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbTipoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbTipoUsuarioActionPerformed

    private void TblDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblDatosMouseClicked
        int filaSeleccionada = TblDatos.rowAtPoint(evt.getPoint());
        
        TxtRut.setText(safe(TblDatos.getValueAt(filaSeleccionada, 0)));
        TxtClave.setText(safe(TblDatos.getValueAt(filaSeleccionada, 1)));
        TxtNombre.setText(safe(TblDatos.getValueAt(filaSeleccionada, 2)));
        TxtApellido.setText(safe(TblDatos.getValueAt(filaSeleccionada, 3)));

        CmbCamiones.setSelectedItem(safe(TblDatos.getValueAt(filaSeleccionada, 4)));
        CmbTipoUsuario.setSelectedItem(safe(TblDatos.getValueAt(filaSeleccionada, 5)));
        tipoUsuarioOriginal = TblDatos.getValueAt(filaSeleccionada,5).toString();
        
        ControladoresGenericos.validarYColorearRut(TxtRut);
        
    }//GEN-LAST:event_TblDatosMouseClicked

    private void TxtRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRutActionPerformed

    private void TxtRutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtRutKeyTyped
        ControladoresGenericos.manejarRut(TxtRut,evt);         
    }//GEN-LAST:event_TxtRutKeyTyped

    
    //modificar campos para buscar
    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        String Rut = TxtRut.getText();
        if(Rut.isEmpty()){
            JOptionPane.showMessageDialog(null,"Ingresa un rut para buscar","Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            Usuario u = UsuariosCrud.buscar(Rut);
            if(u != null){
                TxtRut.setText(u.getRut());
                TxtNombre.setText(u.getNombre());
                TxtApellido.setText(u.getApellido());
                TxtClave.setText(u.getClave());
                CmbCamiones.setSelectedItem(u.getIdCamion());
                CmbTipoUsuario.setSelectedItem(u.getTipoUsuario());


            }else{
                JOptionPane.showMessageDialog(null,"Empleado no encontrado","Advertencia", JOptionPane.WARNING_MESSAGE);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Faltan campos por completar","Advertencia", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
        String rut = TxtRut.getText();
        if (rut.isEmpty()) {
            JOptionPane.showMessageDialog(this,"Por favor ingresa un rut","Alert",JOptionPane.WARNING_MESSAGE);
            return;
        }
        String tipoUsuario;

        String nombre = TxtNombre.getText();
        String usuario = TxtApellido.getText();
        String clave = TxtClave.getText();
        
        if(tipoUsuarioOriginal.equalsIgnoreCase("Super admin")){
            tipoUsuario = "Super admin";
        }else{
            tipoUsuario = (String) CmbTipoUsuario.getSelectedItem();
        }
        
        String idCamion = (String)CmbCamiones.getSelectedItem();
        
        u.setRut(rut);
        u.setNombre(nombre);
        u.setApellido(usuario);
        u.setClave(clave);
        u.setTipoUsuario(tipoUsuario);
        u.setIdCamion(idCamion);

        UsuariosCrud.actualizar(u);
        
        MostrarDatosTabla();

    }//GEN-LAST:event_BtnModificarActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        String Rut = TxtRut.getText();
        if(Rut.isEmpty()){
            JOptionPane.showMessageDialog(null,"Ingresa un rut para eliminar","Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int Confirm = JOptionPane.showConfirmDialog(this, "Estas seguro de eliminar a este Empleado?","Confirmacion",JOptionPane.YES_NO_OPTION);

        if(Confirm == JOptionPane.YES_OPTION){
            UsuariosCrud.eiliminar(Rut);

        }
        MostrarDatosTabla();
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
       TxtRut.setText(null);
       TxtApellido.setText(null);
       TxtClave.setText(null);
       TxtNombre.setText(null);
       CmbCamiones.setSelectedIndex(0);
       CmbTipoUsuario.setSelectedIndex(0);
       
       
    }//GEN-LAST:event_BtnLimpiarActionPerformed

    private void BtnRecargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRecargaActionPerformed
        MostrarDatosTabla();
    }//GEN-LAST:event_BtnRecargaActionPerformed

    private void CmbCamionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbCamionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbCamionesActionPerformed

    private void TxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JButton BtnRecarga;
    private javax.swing.JButton BtnRegistrar;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JComboBox<String> CmbCamiones;
    private javax.swing.JComboBox<String> CmbTipoUsuario;
    private javax.swing.JLabel LblApellido;
    private javax.swing.JLabel LblCamiones;
    private javax.swing.JLabel LblContraseña;
    private javax.swing.JLabel LblNombre;
    private javax.swing.JLabel LblRut;
    private javax.swing.JLabel LblTipoUsuario;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JLabel LblTotalUsuarios;
    private javax.swing.JTable TblDatos;
    private javax.swing.JTextField TxtApellido;
    private javax.swing.JTextField TxtClave;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtRut;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
